// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Logs in a user using their IMAP credentials and sets a secure session cookie.",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Authenticate user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Email address of the user",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Password of the user",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Optional custom IMAP host (defaults to server config)",
                        "name": "imap_host",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success response containing username",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Required parameters missing or too long",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Invalid credentials or IMAP server unreachable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Session error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "Invalidates the user's active session and deletes the session cookie.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Log out user",
                "responses": {
                    "200": {
                        "description": "Success status",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Returns the active session username and global UI date/time format.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Current user profile",
                "responses": {
                    "200": {
                        "description": "Session details containing username and datetime_format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/quota": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Fetches the user's active IMAP mailbox storage usage and limit in bytes.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "IMAP storage quota",
                "responses": {
                    "200": {
                        "description": "Quota details containing used and limit bytes",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer",
                                "format": "int64"
                            }
                        }
                    }
                }
            }
        },
        "/folders": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Returns the complete hierarchical list of IMAP mailboxes/folders with unseen/total counts and tree structure metadata.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mailbox"
                ],
                "summary": "List IMAP folders",
                "responses": {
                    "200": {
                        "description": "Success response containing the list of folders",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/imap.MailboxInfo"
                            }
                        }
                    }
                }
            }
        },
        "/mail/{mailbox}": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Returns a paginated list of email message envelopes for the specified folder, ordered newest first.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mailbox"
                ],
                "summary": "List emails in mailbox",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Mailbox folder name (e.g. INBOX, Drafts, Sent, Trash)",
                        "name": "mailbox",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number (defaults to 1)",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success response containing mailbox, messages, page, and total count",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Mailbox not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/settings": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Returns the logged-in user's complete UI settings and preferences (e.g. theme, timezone, signatures, out of office status).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "Get user preferences",
                "responses": {
                    "200": {
                        "description": "Success response containing settings details",
                        "schema": {
                            "$ref": "#/definitions/handler.settingsResponse"
                        }
                    },
                    "500": {
                        "description": "User lookup or database retrieval failure",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.settingsResponse": {
            "type": "object",
            "properties": {
                "compose_html": {
                    "type": "boolean"
                },
                "date_format": {
                    "type": "string"
                },
                "oof_enabled": {
                    "type": "boolean"
                },
                "oof_message": {
                    "type": "string"
                },
                "rows_per_page": {
                    "type": "integer"
                },
                "signature_pos": {
                    "type": "string"
                },
                "timezone": {
                    "type": "string"
                }
            }
        },
        "imap.MailboxInfo": {
            "type": "object",
            "properties": {
                "delim": {
                    "type": "string"
                },
                "depth": {
                    "description": "nesting level (0 = top-level)",
                    "type": "integer"
                },
                "displayName": {
                    "description": "last path segment (used for tree display)",
                    "type": "string"
                },
                "hasChildren": {
                    "description": "true if at least one subfolder exists under this folder",
                    "type": "boolean"
                },
                "iconType": {
                    "description": "\"inbox\" | \"drafts\" | \"sent\" | \"trash\" | \"junk\" | \"folder\"",
                    "type": "string"
                },
                "isSystem": {
                    "description": "true for INBOX, Sent, Drafts, Trash — cannot be renamed or deleted",
                    "type": "boolean"
                },
                "isTrash": {
                    "type": "boolean"
                },
                "messages": {
                    "type": "integer",
                    "format": "int32"
                },
                "name": {
                    "type": "string"
                },
                "noSelect": {
                    "description": "true when the folder is a hierarchy placeholder (\\Noselect)",
                    "type": "boolean"
                },
                "paddingLeft": {
                    "description": "left-padding in px for tree indentation in the UI",
                    "type": "integer"
                },
                "parentName": {
                    "description": "full name of the parent folder; empty for top-level",
                    "type": "string"
                },
                "unseen": {
                    "type": "integer",
                    "format": "int32"
                }
            }
        }
    },
    "securityDefinitions": {
        "CookieAuth": {
            "description": "The session cookie 'gorc_session' is required for authenticated endpoints.",
            "type": "apiKey",
            "name": "Cookie",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Go-Cubemail API",
	Description:      "Self-hosted webmail application API backed by IMAP and SMTP.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
